test = {   'name': 'q1c',
    'points': 1,
    'suites': [   {   'cases': [   {   'code': '>>> type(q1c_1) == bool\nTrue',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> type(q1c_2) == bool\nTrue',
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
