test = {   'name': 'q5b',
    'points': 1,
    'suites': [   {   'cases': [   {   'code': '>>> 0 <= q5bi <= 9\nTrue',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> 0 <= q5bii <= 9\nTrue',
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
