test = {   'name': 'q6b',
    'points': 2,
    'suites': [   {   'cases': [   {   'code': '>>> all(sample <= 100)\nTrue',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> all(sample >= 0)\nTrue',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> len(sample)\n10',
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
