test = {   'name': 'q2f',
    'points': 1,
    'suites': [   {   'cases': [   {   'code': '>>> pattern\n'
                                               "('26', 'Jan', '2014')",
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': ">>> pattern[0] == '26'\nTrue",
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': ">>> pattern[1] == 'Jan'\nTrue",
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': ">>> pattern[2] == '2014'\nTrue",
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
