test = {   'name': 'q1d',
    'points': 1,
    'suites': [   {   'cases': [   {   'code': '>>> len(theta) == 4\nTrue',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> all(Y_hat == X @ theta)\n'
                                               'True',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> loss >= 0\nTrue',
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
