test = {   'name': 'q2a',
    'points': 1,
    'suites': [   {   'cases': [   {   'code': '>>> len(X) == 53940\nTrue',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> len(X[0]) == 9\nTrue',
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
