test = {   'name': 'q8b',
    'points': 1,
    'suites': [   {   'cases': [   {   'code': '>>> training_error > 0\nTrue',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> test_error > 0\nTrue',
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
